/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as appIndexRouteImport } from './routes/(app)/index'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as appStaffIndexRouteImport } from './routes/(app)/staff/index'
import { Route as appReportsIndexRouteImport } from './routes/(app)/reports/index'
import { Route as appReportsTrafficRouteImport } from './routes/(app)/reports/traffic'
import { Route as appReportsSalesRouteImport } from './routes/(app)/reports/sales'

const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const appIndexRoute = appIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)
const appStaffIndexRoute = appStaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => appRouteRoute,
} as any)
const appReportsIndexRoute = appReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => appRouteRoute,
} as any)
const appReportsTrafficRoute = appReportsTrafficRouteImport.update({
  id: '/reports/traffic',
  path: '/reports/traffic',
  getParentRoute: () => appRouteRoute,
} as any)
const appReportsSalesRoute = appReportsSalesRouteImport.update({
  id: '/reports/sales',
  path: '/reports/sales',
  getParentRoute: () => appRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof authLoginRoute
  '/': typeof appIndexRoute
  '/reports/sales': typeof appReportsSalesRoute
  '/reports/traffic': typeof appReportsTrafficRoute
  '/reports': typeof appReportsIndexRoute
  '/staff': typeof appStaffIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof authLoginRoute
  '/': typeof appIndexRoute
  '/reports/sales': typeof appReportsSalesRoute
  '/reports/traffic': typeof appReportsTrafficRoute
  '/reports': typeof appReportsIndexRoute
  '/staff': typeof appStaffIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appRouteRouteWithChildren
  '/(auth)': typeof authRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(app)/': typeof appIndexRoute
  '/(app)/reports/sales': typeof appReportsSalesRoute
  '/(app)/reports/traffic': typeof appReportsTrafficRoute
  '/(app)/reports/': typeof appReportsIndexRoute
  '/(app)/staff/': typeof appStaffIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/'
    | '/reports/sales'
    | '/reports/traffic'
    | '/reports'
    | '/staff'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/reports/sales'
    | '/reports/traffic'
    | '/reports'
    | '/staff'
  id:
    | '__root__'
    | '/(app)'
    | '/(auth)'
    | '/(auth)/login'
    | '/(app)/'
    | '/(app)/reports/sales'
    | '/(app)/reports/traffic'
    | '/(app)/reports/'
    | '/(app)/staff/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
  authRouteRoute: typeof authRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/': {
      id: '/(app)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(app)/staff/': {
      id: '/(app)/staff/'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof appStaffIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/reports/': {
      id: '/(app)/reports/'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof appReportsIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/reports/traffic': {
      id: '/(app)/reports/traffic'
      path: '/reports/traffic'
      fullPath: '/reports/traffic'
      preLoaderRoute: typeof appReportsTrafficRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/reports/sales': {
      id: '/(app)/reports/sales'
      path: '/reports/sales'
      fullPath: '/reports/sales'
      preLoaderRoute: typeof appReportsSalesRouteImport
      parentRoute: typeof appRouteRoute
    }
  }
}

interface appRouteRouteChildren {
  appIndexRoute: typeof appIndexRoute
  appReportsSalesRoute: typeof appReportsSalesRoute
  appReportsTrafficRoute: typeof appReportsTrafficRoute
  appReportsIndexRoute: typeof appReportsIndexRoute
  appStaffIndexRoute: typeof appStaffIndexRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appIndexRoute: appIndexRoute,
  appReportsSalesRoute: appReportsSalesRoute,
  appReportsTrafficRoute: appReportsTrafficRoute,
  appReportsIndexRoute: appReportsIndexRoute,
  appStaffIndexRoute: appStaffIndexRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

interface authRouteRouteChildren {
  authLoginRoute: typeof authLoginRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authLoginRoute: authLoginRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
  authRouteRoute: authRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
