/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as appIndexRouteImport } from './routes/(app)/index'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as app403RouteImport } from './routes/(app)/403'
import { Route as appUsersIndexRouteImport } from './routes/(app)/users/index'
import { Route as appUsersCreateRouteImport } from './routes/(app)/users/create'
import { Route as appUsersIdIndexRouteImport } from './routes/(app)/users/$id/index'
import { Route as appUsersIdEditRouteImport } from './routes/(app)/users/$id/edit'

const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const appIndexRoute = appIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)
const app403Route = app403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => appRouteRoute,
} as any)
const appUsersIndexRoute = appUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => appRouteRoute,
} as any)
const appUsersCreateRoute = appUsersCreateRouteImport.update({
  id: '/users/create',
  path: '/users/create',
  getParentRoute: () => appRouteRoute,
} as any)
const appUsersIdIndexRoute = appUsersIdIndexRouteImport.update({
  id: '/users/$id/',
  path: '/users/$id/',
  getParentRoute: () => appRouteRoute,
} as any)
const appUsersIdEditRoute = appUsersIdEditRouteImport.update({
  id: '/users/$id/edit',
  path: '/users/$id/edit',
  getParentRoute: () => appRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/403': typeof app403Route
  '/login': typeof authLoginRoute
  '/': typeof appIndexRoute
  '/users/create': typeof appUsersCreateRoute
  '/users': typeof appUsersIndexRoute
  '/users/$id/edit': typeof appUsersIdEditRoute
  '/users/$id': typeof appUsersIdIndexRoute
}
export interface FileRoutesByTo {
  '/403': typeof app403Route
  '/login': typeof authLoginRoute
  '/': typeof appIndexRoute
  '/users/create': typeof appUsersCreateRoute
  '/users': typeof appUsersIndexRoute
  '/users/$id/edit': typeof appUsersIdEditRoute
  '/users/$id': typeof appUsersIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appRouteRouteWithChildren
  '/(auth)': typeof authRouteRouteWithChildren
  '/(app)/403': typeof app403Route
  '/(auth)/login': typeof authLoginRoute
  '/(app)/': typeof appIndexRoute
  '/(app)/users/create': typeof appUsersCreateRoute
  '/(app)/users/': typeof appUsersIndexRoute
  '/(app)/users/$id/edit': typeof appUsersIdEditRoute
  '/(app)/users/$id/': typeof appUsersIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/403'
    | '/login'
    | '/'
    | '/users/create'
    | '/users'
    | '/users/$id/edit'
    | '/users/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/403'
    | '/login'
    | '/'
    | '/users/create'
    | '/users'
    | '/users/$id/edit'
    | '/users/$id'
  id:
    | '__root__'
    | '/(app)'
    | '/(auth)'
    | '/(app)/403'
    | '/(auth)/login'
    | '/(app)/'
    | '/(app)/users/create'
    | '/(app)/users/'
    | '/(app)/users/$id/edit'
    | '/(app)/users/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
  authRouteRoute: typeof authRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/': {
      id: '/(app)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(app)/403': {
      id: '/(app)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof app403RouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/users/': {
      id: '/(app)/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof appUsersIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/users/create': {
      id: '/(app)/users/create'
      path: '/users/create'
      fullPath: '/users/create'
      preLoaderRoute: typeof appUsersCreateRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/users/$id/': {
      id: '/(app)/users/$id/'
      path: '/users/$id'
      fullPath: '/users/$id'
      preLoaderRoute: typeof appUsersIdIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/users/$id/edit': {
      id: '/(app)/users/$id/edit'
      path: '/users/$id/edit'
      fullPath: '/users/$id/edit'
      preLoaderRoute: typeof appUsersIdEditRouteImport
      parentRoute: typeof appRouteRoute
    }
  }
}

interface appRouteRouteChildren {
  app403Route: typeof app403Route
  appIndexRoute: typeof appIndexRoute
  appUsersCreateRoute: typeof appUsersCreateRoute
  appUsersIndexRoute: typeof appUsersIndexRoute
  appUsersIdEditRoute: typeof appUsersIdEditRoute
  appUsersIdIndexRoute: typeof appUsersIdIndexRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  app403Route: app403Route,
  appIndexRoute: appIndexRoute,
  appUsersCreateRoute: appUsersCreateRoute,
  appUsersIndexRoute: appUsersIndexRoute,
  appUsersIdEditRoute: appUsersIdEditRoute,
  appUsersIdIndexRoute: appUsersIdIndexRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

interface authRouteRouteChildren {
  authLoginRoute: typeof authLoginRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authLoginRoute: authLoginRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
  authRouteRoute: authRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
